// Copyright (c) Rodel. All rights reserved.
// <auto-generated />

namespace RodelAgent.UI.Models.Constants;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    AppTheme,
    HideWhenCloseWindow,
    ShouldAskBeforeWindowClosed,
    ShouldSkipStartup,
    WorkingDirectory,
    LastSelectedFeature,
    IsMainWindowMaximized,
    MainWindowPositionLeft,
    MainWindowPositionTop,
    MainWindowHeight,
    MainWindowWidth,
    UseStreamOutput,
    ChatServicePageServiceColumnWidth,
    ChatServicePageExtraColumnWidth,
    LastSelectedChatService,
    ChatServicePageIsEnterSend,
    ChatSessionPanelType,
    ChatServicePageExtraColumnVisible,
    ChatServicePageExtraRowHeight,
    LastSelectedAgent,
    LastSelectedSessionPreset,
    DeletingPluginIds,
    LastSelectedTranslateService,
    ShouldRecordTranslate,
    LastSelectedDrawService,
    DrawHistoryColumnWidth,
    DrawServicePageIsEnterSend,
    LastSelectedAudioService,
    AudioHistoryColumnWidth,
    AudioServicePageIsEnterSend,
    IsMigrating,
    LastSelectedGroup,
    ChatGroupPanelType,
    AppLanguage,
    IsChatServicePageServiceColumnManualHide,
    IsChatServicePageExtraColumnManualHide,
    IsDrawHistoryColumnManualHide,
    IsAudioHistoryColumnManualHide,
    LastSelectedFeaturePage,
    IsInternalPromptTest,
    PromptTestLastSelectedChatService,
    PromptTestLastSelectedModel,
    PromptTestPageExtraColumnWidth,
    PromptTestMessageJsonFilePath,
    PromptTestSystemPromptPath,
    PromptTestPresetVariablesFilePath,
    PromptTestInputFilePath,
}
#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
