// Copyright (c) Rodel. All rights reserved.
// <auto-generated />

namespace RodelAgent.UI.Models.Constants;

/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    AppTheme,
    HideWhenCloseWindow,
    ShouldAskBeforeWindowClosed,
    ShouldSkipStartup,
    WorkingDirectory,
    LastSelectedFeature,
    IsMainWindowMaximized,
    MainWindowPositionLeft,
    MainWindowPositionTop,
    MainWindowHeight,
    MainWindowWidth,
    UseStreamOutput,
    ChatServicePageServiceColumnWidth,
    ChatServicePageExtraColumnWidth,
    LastSelectedChatService,
    ChatServicePageIsEnterSend,
    ChatSessionPanelType,
    ChatServicePageExtraColumnVisible,
    ChatServicePageExtraRowHeight,
    LastSelectedAgent,
    LastSelectedSessionPreset,
    DeletingPluginIds,
    LastSelectedTranslateService,
    ShouldRecordTranslate,
    LastSelectedDrawService,
    DrawHistoryColumnWidth,
    DrawServicePageIsEnterSend,
    LastSelectedAudioService,
    AudioHistoryColumnWidth,
    AudioServicePageIsEnterSend,
    IsMigrating,
    LastSelectedGroup,
    ChatGroupPanelType,
    AppLanguage,
}
