// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

namespace RodelAgent.UI.Models.Constants;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    AppTheme,
    HideWhenCloseWindow,
    ShouldAskBeforeWindowClosed,
    ShouldSkipStartup,
    WorkingDirectory,
    LastSelectedFeature,
    IsMainWindowMaximized,
    MainWindowPositionLeft,
    MainWindowPositionTop,
    MainWindowHeight,
    MainWindowWidth,
    UseStreamOutput,
    LastSelectedChatService,
    ChatServicePageIsEnterSend,
    ChatSessionPanelType,
    LastSelectedAgent,
    LastSelectedSessionPreset,
    DeletingPluginIds,
    LastSelectedTranslateService,
    ShouldRecordTranslate,
    LastSelectedDrawService,
    DrawServicePageIsEnterSend,
    LastSelectedAudioService,
    AudioServicePageIsEnterSend,
    IsMigrating,
    LastSelectedGroup,
    ChatGroupPanelType,
    AppLanguage,
    LastSelectedFeaturePage,
    IsInternalPromptTest,
    PromptTestLastSelectedChatService,
    PromptTestLastSelectedModel,
    PromptTestPageExtraColumnWidth,
    PromptTestMessageJsonFilePath,
    PromptTestSystemPromptPath,
    PromptTestPresetVariablesFilePath,
    PromptTestInputFilePath,
    AppVersion,
    MigrationFailed,
    LastSelectedAgentSection,
    ChatServicePageHistoryHeight,
    ChatSessionIsInstructionVisible,
    ChatSessionIsOptionsVisible,
    GroupSessionIsAgentsVisible,
    GroupSessionIsOptionsVisible,
    IsChatServicesCollapsed,
    IsChatAgentsCollapsed,
    IsChatGroupsCollapsed,
    AutoRunMcpServer,
}
#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
