// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RodelAgent.Context.Migrations
{
    /// <inheritdoc />
    public partial class ChatAddGroup : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Sessions",
                table: "Sessions");

            migrationBuilder.RenameTable(
                name: "Sessions",
                newName: "Metadata");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Metadata",
                table: "Metadata",
                column: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Metadata",
                table: "Metadata");

            migrationBuilder.RenameTable(
                name: "Metadata",
                newName: "Sessions");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Sessions",
                table: "Sessions",
                column: "Id");
        }
    }
}
