//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RodelAudio.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AudioService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AudioService() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RodelAudio.Console.Properties.AudioService", typeof(AudioService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Azure 语音 的本地化字符串。
        /// </summary>
        internal static string AzureSpeech {
            get {
                return ResourceManager.GetString("AzureSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中，请稍候... 的本地化字符串。
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个合适的模型 的本地化字符串。
        /// </summary>
        internal static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个文本转语音服务 的本地化字符串。
        /// </summary>
        internal static string SelectProvider {
            get {
                return ResourceManager.GetString("SelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个音频 的本地化字符串。
        /// </summary>
        internal static string SelectVoice {
            get {
                return ResourceManager.GetString("SelectVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音已保存 的本地化字符串。
        /// </summary>
        internal static string SpeechSaved {
            get {
                return ResourceManager.GetString("SpeechSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        internal static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
    }
}
