// Copyright (c) Rodel. All rights reserved.
// <auto-generated />

using Microsoft.UI.Xaml.Documents;

namespace RodelAgent.UI.Controls.Markdown.TextElements;

public interface IAddChild
{
    TextElement TextElement { get; }
    void AddChild(IAddChild child);
}
