// Copyright (c) Richasy. All rights reserved.

using RodelTranslate.Models.Client;

namespace RodelTranslate.Core;

/// <summary>
/// 预定义的语言.
/// </summary>
internal static partial class PredefinedLanguages
{
    internal static List<Language> AzureLanguages { get; } = new List<Language>
    {
        new ("af", "af"),
        new ("am", "am"),
        new ("ar", "ar"),
        new ("as", "as"),
        new ("az", "az"),
        new ("ba", "ba"),
        new ("bg", "bg"),
        new ("bho", "bho"),
        new ("bn", "bn"),
        new ("bo", "bo"),
        new ("brx", "brx"),
        new ("bs", "bs"),
        new ("ca", "ca"),
        new ("cs", "cs"),
        new ("cy", "cy"),
        new ("da", "da"),
        new ("de", "de"),
        new ("doi", "doi"),
        new ("dsb", "dsb"),
        new ("dv", "dv"),
        new ("el", "el"),
        new ("en", "en"),
        new ("es", "es"),
        new ("et", "et"),
        new ("eu", "eu"),
        new ("fa", "fa"),
        new ("fi", "fi"),
        new ("fil", "fil"),
        new ("fj", "fj"),
        new ("fo", "fo"),
        new ("fr", "fr"),
        new ("fr-CA", "fr-CA"),
        new ("ga", "ga"),
        new ("gl", "gl"),
        new ("gom", "gom"),
        new ("gu", "gu"),
        new ("ha", "ha"),
        new ("he", "he"),
        new ("hi", "hi"),
        new ("hr", "hr"),
        new ("hsb", "hsb"),
        new ("ht", "ht"),
        new ("hu", "hu"),
        new ("hy", "hy"),
        new ("id", "id"),
        new ("ig", "ig"),
        new ("is", "is"),
        new ("iu", "iu"),
        new ("iu-Latn", "iu-Latn"),
        new ("ja", "ja"),
        new ("ka", "ka"),
        new ("kk", "kk"),
        new ("km", "km"),
        new ("kn", "kn"),
        new ("ko", "ko"),
        new ("ks", "ks"),
        new ("ku", "ku"),
        new ("ky", "ky"),
        new ("ln", "ln"),
        new ("lo", "lo"),
        new ("lt", "lt"),
        new ("lug", "lug"),
        new ("lv", "lv"),
        new ("lzh", "lzh"),
        new ("mai", "mai"),
        new ("mg", "mg"),
        new ("mi", "mi"),
        new ("mk", "mk"),
        new ("ml", "ml"),
        new ("mn-Cyrl", "mn-Cyrl"),
        new ("mn-Mong", "mn-Mong"),
        new ("mni", "mni"),
        new ("mr", "mr"),
        new ("ms", "ms"),
        new ("mt", "mt"),
        new ("my", "my"),
        new ("nb", "nb"),
        new ("ne", "ne"),
        new ("nl", "nl"),
        new ("nso", "nso"),
        new ("nya", "nya"),
        new ("or", "or"),
        new ("pa", "pa"),
        new ("pl", "pl"),
        new ("ps", "ps"),
        new ("pt", "pt"),
        new ("pt-PT", "pt-PT"),
        new ("ro", "ro"),
        new ("ru", "ru"),
        new ("run", "run"),
        new ("rw", "rw"),
        new ("sd", "sd"),
        new ("si", "si"),
        new ("sk", "sk"),
        new ("sl", "sl"),
        new ("sm", "sm"),
        new ("sn", "sn"),
        new ("so", "so"),
        new ("sq", "sq"),
        new ("sr-Cyrl", "sr-Cyrl"),
        new ("sr-Latn", "sr-Latn"),
        new ("st", "st"),
        new ("sv", "sv"),
        new ("sw", "sw"),
        new ("ta", "ta"),
        new ("te", "te"),
        new ("th", "th"),
        new ("ti", "ti"),
        new ("tk", "tk"),
        new ("tlh-Latn", "tlh-Latn"),
        new ("tlh-Piqd", "tlh-Piqd"),
        new ("tn", "tn"),
        new ("to", "to"),
        new ("tr", "tr"),
        new ("tt", "tt"),
        new ("ty", "ty"),
        new ("ug", "ug"),
        new ("uk", "uk"),
        new ("ur", "ur"),
        new ("uz", "uz"),
        new ("vi", "vi"),
        new ("xh", "xh"),
        new ("yo", "yo"),
        new ("yue", "yue"),
        new ("zh-Hans", "zh-Hans"),
        new ("zh-Hant", "zh-Hant"),
        new ("zu", "zu"),
    };
}
