// Copyright (c) Richasy. All rights reserved.

using RodelTranslate.Models.Client;

namespace RodelTranslate.Core;

/// <summary>
/// 预定义的语言.
/// </summary>
internal static partial class PredefinedLanguages
{
    internal static List<Language> YoudaoLanguages { get; } = new List<Language>
    {
        new ("ar", "ar"),
        new ("de", "de"),
        new ("en", "en"),
        new ("es", "es"),
        new ("fr", "fr"),
        new ("hi", "hi"),
        new ("id", "id"),
        new ("it", "it"),
        new ("ja", "ja"),
        new ("ko", "ko"),
        new ("nl", "nl"),
        new ("pt", "pt"),
        new ("ru", "ru"),
        new ("th", "th"),
        new ("vi", "vi"),
        new ("zh-CHS", "zh-CHS"),
        new ("zh-CHT", "zh-CHT"),
        new ("af", "af"),
        new ("am", "am"),
        new ("az", "az"),
        new ("be", "be"),
        new ("bg", "bg"),
        new ("bn", "bn"),
        new ("bs", "bs"),
        new ("ca", "ca"),
        new ("ceb", "ceb"),
        new ("co", "co"),
        new ("cs", "cs"),
        new ("cy", "cy"),
        new ("da", "da"),
        new ("el", "el"),
        new ("eo", "eo"),
        new ("et", "et"),
        new ("eu", "eu"),
        new ("fa", "fa"),
        new ("fi", "fi"),
        new ("fj", "fj"),
        new ("ga", "ga"),
        new ("gd", "gd"),
        new ("gl", "gl"),
        new ("gu", "gu"),
        new ("ha", "ha"),
        new ("haw", "haw"),
        new ("he", "he"),
        new ("hr", "hr"),
        new ("ht", "ht"),
        new ("hu", "hu"),
        new ("hy", "hy"),
        new ("ig", "ig"),
        new ("is", "is"),
        new ("jw", "jw"),
        new ("ka", "ka"),
        new ("kk", "kk"),
        new ("km", "km"),
        new ("kn", "kn"),
        new ("ku", "ku"),
        new ("ky", "ky"),
        new ("la", "la"),
        new ("lb", "lb"),
        new ("lo", "lo"),
        new ("lt", "lt"),
        new ("lv", "lv"),
        new ("mg", "mg"),
        new ("mi", "mi"),
        new ("mk", "mk"),
        new ("ml", "ml"),
        new ("mn", "mn"),
        new ("mr", "mr"),
        new ("ms", "ms"),
        new ("mt", "mt"),
        new ("my", "my"),
        new ("ne", "ne"),
        new ("no", "no"),
        new ("nl", "nl"),
        new ("ny", "ny"),
        new ("pa", "pa"),
        new ("pl", "pl"),
        new ("ps", "ps"),
        new ("ro", "ro"),
        new ("sd", "sd"),
        new ("si", "si"),
        new ("sk", "sk"),
        new ("sl", "sl"),
        new ("sm", "sm"),
        new ("sn", "sn"),
        new ("so", "so"),
        new ("sq", "sq"),
        new ("sr-Cyrl", "sr-Cyrl"),
        new ("sr-Latn", "sr-Latn"),
        new ("st", "st"),
        new ("su", "su"),
        new ("sv", "sv"),
        new ("sw", "sw"),
        new ("ta", "ta"),
        new ("te", "te"),
        new ("tg", "tg"),
        new ("tl", "tl"),
        new ("tlh", "tlh"),
        new ("to", "to"),
        new ("tr", "tr"),
        new ("ty", "ty"),
        new ("uk", "uk"),
        new ("ur", "ur"),
        new ("uz", "uz"),
        new ("xh", "xh"),
        new ("yi", "yi"),
        new ("yo", "yo"),
        new ("yue", "yue"),
        new ("zu", "zu"),
    };
}
