// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

using Microsoft.UI.Xaml.Documents;

namespace RodelAgent.UI.Controls.Markdown.TextElements;

internal class MyInlineText : IAddChild
{
    private Run _run;

    public TextElement TextElement => _run;

    public MyInlineText(string text)
    {
        _run = new Run()
        {
            Text = text,
        };
    }

    public void AddChild(IAddChild child)
    {
    }
}
