//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RodelTranslate.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslateService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslateService() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RodelTranslate.Console.Properties.TranslateService", typeof(TranslateService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 阿里 的本地化字符串。
        /// </summary>
        internal static string AliTranslate {
            get {
                return ResourceManager.GetString("AliTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Azure / 必应 的本地化字符串。
        /// </summary>
        internal static string AzureTranslate {
            get {
                return ResourceManager.GetString("AzureTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度 的本地化字符串。
        /// </summary>
        internal static string BaiduTranslate {
            get {
                return ResourceManager.GetString("BaiduTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谷歌 的本地化字符串。
        /// </summary>
        internal static string GoogleTranslate {
            get {
                return ResourceManager.GetString("GoogleTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选 的本地化字符串。
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中，请稍候... 的本地化字符串。
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在释放本地资源 的本地化字符串。
        /// </summary>
        internal static string ReleasingLocalResource {
            get {
                return ResourceManager.GetString("ReleasingLocalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒 的本地化字符串。
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标语言 的本地化字符串。
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个翻译服务 的本地化字符串。
        /// </summary>
        internal static string SelectProvider {
            get {
                return ResourceManager.GetString("SelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腾讯 的本地化字符串。
        /// </summary>
        internal static string TencentTranslate {
            get {
                return ResourceManager.GetString("TencentTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        internal static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火山 的本地化字符串。
        /// </summary>
        internal static string VolcanoTranslate {
            get {
                return ResourceManager.GetString("VolcanoTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讯飞 的本地化字符串。
        /// </summary>
        internal static string XunfeiTranslate {
            get {
                return ResourceManager.GetString("XunfeiTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有道 的本地化字符串。
        /// </summary>
        internal static string YoudaoTranslate {
            get {
                return ResourceManager.GetString("YoudaoTranslate", resourceCulture);
            }
        }
    }
}
