//<auto-generated/>
using System.ComponentModel;
using Microsoft.SemanticKernel;

public sealed class TestPlugin
{
    [KernelFunction]
    [Description("Get BiliBili hot search")]
    public static string GetBiliBiliHotSearch()
    {
        return """
            1. 《鬼灭之刃》
            2. 《刺客伍六七》
            3. 《狐妖小红娘》
            4. 《斗罗大陆》
            5. 《海贼王》
            """;
    }
}
