//<auto-generated/>
using System.ComponentModel;
using Microsoft.SemanticKernel;

public sealed class TestPlugin
{
    [KernelFunction]
    [Description("根据关键词查询BiliBili(B站)的热搜。")]
    public static string GetBiliBiliHotSearch([Description("搜索关键词，比如老虎。")]string keyword)
    {
        return """
            1. 《鬼灭之刃》
            2. 《刺客伍六七》
            3. 《狐妖小红娘》
            4. 《斗罗大陆》
            5. 《海贼王》
            """;
    }
}
